services:
  - type: web
    name: pasalo-api
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install --legacy-peer-deps && npx prisma generate && npm run build
    startCommand: npx prisma migrate deploy && npm run start:prod
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pasalo-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CLOUDINARY_URL
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    autoDeploy: false

databases:
  - name: pasalo-db
    databaseName: pasalo
    user: pasalo
    plan: free
